# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
modelArts_mode: False
is_distributed: False
# Url for modelarts
data_url: ""
train_url: ""
# Path for local
dataroot: "/home/ma-user/work/data"
device_target: "Ascend"
rank: 0
group_size: 1

# ==============================================================================
# options
seed: 0
num_train: 83560
momentum: 0.5
DBN_numepochs: 30
NN_numepochs: 100
batchsize: 100
alpha: 0.1
wd: 0.0001 #1e-4
checkpoint_path: "./nn.ckpt"
ckpt_save_dir: "./ckpt/"

# optimizer and lr related
optimizer: sgd
freq: 10.0
lr: 2.0
lr_decay: 1e-6

---

# Help description for each configuration
modelArts_mode: "Whether training on modelarts, default: False"
data_url: "Url for modelarts"
train_url: "Url for modelarts"
data_path: "The location of the input data."
output_path: "The location of the output file."
device_target: 'Target device type'