---

model: 'nbeats'
data: 'M3C'
root_path: './mindseq/data/M3C/'
data_path: 'M3_Year.csv'
device: "GPU"
freq: 'Y'
train_epochs: 500
batch_size: 1024
seq_len: 5
pred_len: 1
seed: 42
do_train: False
ckpt_path: "./checkpoints/Nbeats-checkpoints/Nbeats_M3C_Year_5_1.ckpt"