---
do_train: False
ckpt_path: "./checkpoints/test_ckpt/Autoformer_ETTh1_96_96_168.ckpt"
model_id: 'test'
model: 'Autoformer'
seed: 2021

data: 'ETTh1'
root_path: './mindseq/data/ETT/'
data_path: 'ETTh1.csv'
features: 'M'
target: 'OT'
freq: 'h'
checkpoints: './checkpoints/'

seq_len: 96
label_len: 96
pred_len: 168

bucket_size: 4
n_hashes: 4
enc_in: 7
dec_in: 7
c_out: 7
d_model: 512
n_heads: 8
e_layers: 2
d_layers: 1
d_ff: 2048
moving_avg: 25
factor: 1
distil: True
dropout: 0.05
embed: 'timeF'
activation: 'gelu'
output_attention: False

num_workers: 10
itr: 1
train_epochs: 10
batch_size: 1
patience: 3
learning_rate: 0.0001
des: 'test'
loss: 'mse'
lradj: 'type1'
use_amp: False

device: "GPU"