__BASE__: [
  '../coco.yml',
]

data:
  is_segment: True
  seg_size: 28
  num_parallel_workers: 4
  train_transforms:
    item_transforms:
      - RandomFlip: { prob: 0.5 }
      - Resize: { target_size: [768, 1280], keep_ratio: True }
      - NormalizeImage: { is_scale: False, norm_type: 'mean_std', mean: [123.675, 116.28, 103.53], std: [58.395, 57.12, 57.375] }
      - TransposeImage: { hwc2chw: True, bgr2rgb: True }
      - LabelsPadding: { padding_size: 128, padding_value: -1 }

  eval_transforms:
    item_transforms:
      - Resize: { target_size: [768, 1280], keep_ratio: True }
      - NormalizeImage: { is_scale: True, norm_type: 'mean_std', mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225] }
      - TransposeImage: { hwc2chw: True }
      - LabelsPadding: { padding_size: 128, padding_value: -1 }
