# --------------------------------------------------
# Builtin Configurations
# 训练数据存储的地方
data_path: '../conll2003'
# 输出ckpt文件的名称
ckpt_save_path: '../ckpt_lstm_crf'
# 设备类型： Ascend, CPU。默认Ascend
device_target: 'CPU'
# 在device_target位Ascend时，指定参与计算的NPU
device_id: 2
# 导出文件的前缀
export_prefix: 'model-crf'
export_suffix: ''

# --------------------------------------------------
# LSTM_CRF CONFIG
# 训练的轮数，默认20轮
num_epochs: 2
# 单次处理数据量的大小，默认16
batch_size: 16
# 组成最大长度
vocab_max_length: 113
# embedding_dim数量，默认384
embedding_dim: 128
# hidden_dim数量，默认384
hidden_dim: 128
num_layers: 2
learning_ratelearning_rate: True
# 学习率过小会导致loss不容易对其，学习率过大会导致预测准确率位0（可以加大epoch解决）
learning_rate: 0.00001

# export.py
model_path: "./"

---
device_target: ['Ascend', 'CPU']
file_format: ['AIR', 'MINDIR']