modelnet_label = [
        "airplane",
        "bathtub",
        "bed",
        "bench",
        "bookshelf",
        "bottle",
        "bowl",
        "car",
        "chair",
        "cone",
        "cup",
        "curtain",
        "desk",
        "door",
        "dresser",
        "flower pot",
        "glass box",
        "guitar",
        "keyboard",
        "lamp",
        "laptop",
        "mantel",
        "monitor",
        "night stand",
        "person",
        "piano",
        "plant",
        "radio",
        "range hood",
        "sink",
        "sofa",
        "stairs",
        "stool",
        "table",
        "tent",
        "toilet",
        "tv stand",
        "vase",
        "wardrobe",
        "xbox"
]

shapenet_label = [
    "table",
    "chair",
    "airplane",
    "car",
    "sofa",
    "rifle",
    "lamp",
    "vessel",
    "bench",
    "loudspeaker",
    "cabinet",
    "display",
    "telephone",
    "bus",
    "bathtub",
    "cellular telephone",
    "guitar",
    "faucet",
    "clock",
    "pot",
    "jar",
    "bottle",
    "laptop",
    "bookshelf",
    "knife",
    "train",
    "ashcan",
    "motorcycle",
    "pistol",
    "file",
    "piano",
    "bed",
    "stove",
    "mug",
    "bowl",
    "washer",
    "printer",
    "helmet",
    "microwave",
    "skateboard",
    "tower",
    "camera",
    "basket",
    "can",
    "pillow",
    "mailbox",
    "dishwasher",
    "rocket",
    "bag",
    "birdhouse",
    "earphone",
    "microphone",
    "remote control",
    "computer keyboard",
    "cap"
]