---

model: JAT
data: ETTh1
root_path: ./mindseq/data/ETT/
data_path: ETTh1.csv
features: S
target: OT
freq: h
checkpoints: ./checkpoints/train_ckpt
seq_len: 96
label_len: 48
pred_len: 24
enc_in: 7
dec_in: 7
c_out: 7
d_model: 512
n_heads: 8
e_layers: 2
d_layers: 1
s_layers: '3,2,1'
d_ff: 2048
factor: 5
padding: 0
distil: true
dropout: 0.05
attn: prob
embed: timeF
activation: gelu
output_attention: false
mix: true
cols: '+'
num_workers: 0
itr: 1
train_epochs: 1
batch_size: 32
patience: 3
learning_rate: 0.0001
des: JAT
loss: mse
lradj: type1
use_amp: false
inverse: false
device: GPU
jat_heads: 2
order: 1
ceof: 0.5
prob_jat: false
factor_jat: 2
jat_sgn: false
super_p: 0.2
do_train: true
ckpt_path: ''
