# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
# Url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# Path for local
data_path: "/cache/data"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path"
device_target: "CPU" # Ascend
need_modelarts_dataset_unzip: True

# ==============================================================================
# options
keep_checkpoint_max: 10
ckpt_save_dir: "./ckpt/"

# export option
ckpt_file: ""
file_name: "net"
file_format: "MINDIR" # AIR,MINDIR,ONNX

####################

# params for dataset and data loader
data_root: "data"
dataset_mean: 0.5
dataset_std: 0.5
batch_size: 50

# params for source dataset
src_dataset: "MNIST"
src_encoder_checkpoint: "ADDA-source-encoder.ckpt"
src_classifier_checkpoint: "ADDA-source-classifier.ckpt"

# params for target dataset
tgt_dataset: "USPS"
tgt_encoder_checkpoint: "ADDA-target-encoder.ckpt"

# params for setting up models
model_root: "checkpoint"
d_input_dims: 500
d_hidden_dims: 500
d_output_dims: 2
d_model_checkpoint: "ADDA-critic.ckpt"

# params for training network
num_epochs_pre: 10 #10
log_step_pre: 600 #200
eval_step_pre: 2 #20
save_step_pre: 2 #100
num_epochs: 60 #2000,600
log_step: 10
save_step: 10
manual_seed: null # None

# params for optimizing models
d_learning_rate: 3.0e-4 #1e-4
c_learning_rate: 1.0e-4
beta1: 0.5
beta2: 0.9
# params for infer
dataset_path: 'data/USPS'
####################
---

# Help description for each configuration
enable_modelarts: "Whether training on modelarts, default: False"
data_url: "Url for modelarts"
train_url: "Url for modelarts"
data_path: "The location of the input data."
output_path: "The location of the output file."
device_target: 'Target device type'
enable_profiling: 'Whether enable profiling while training, default: False'
