python3 ./src/run_speech_ms.py \
    --data_dir ./Datasets \
    --model_type speech_bert \
    --model_name_or_path bert-base-uncased \
    --task_name ontoevent-doc \
    --central_task token \
    --ere_task_type doc_all \
    --output_dir ./history_models/trigger-classification_ontoevent-doc_speech-bert \
    --cache_dir /your/cache_dir \
    --max_seq_length 32 \
    --max_mention_size 10 \
    --do_lower_case \
    --gradient_accumulation_steps 4 \
    --learning_rate 5e-5 \
    --num_train_epochs 100 \
    --save_steps 500 \
    --logging_steps 500 \
    --seed 42 \
    --do_train \
    --do_eval \
    --do_test \
    --evaluate_during_training \
    --overwrite_output_dir \
    --no_cuda \
