# Builtin Configurations
data_path: "../conll2003"
ckpt_save_path: '../ckpt_lstm_crf'
device_target: 'CPU'
device_id: 1
enable_profiling: False

# LSTM_CRF CONFIG
num_epochs: 20
batch_size: 20
embed_size: 300
num_hidden: 320
num_layers: 2
bidirectional: True

# train.py
device_num: 1
data_CoNLL_path: "../data/conll2003"

# export.py
model_format: "MINDIR"
model_path: "./"
ckpt_path: "./lstm-crf.ckpt"

---
device_target: ['Ascend', 'CPU']
file_format: ['AIR', 'MINDIR']
