data:
  dataset_dir: "/data1/cityscapes"
  name: "cityscapes"
  num_parallel_workers: 8
  map_label: [0.8373, 0.918, 0.866, 1.0345,
              1.0166, 0.9969, 0.9754, 1.0489,
              0.8786, 1.0023, 0.9539, 0.9843,
              1.1116, 0.9037, 1.0865, 1.0955,
              1.0865, 1.1529, 1.0507]
  ignore_label: 255
  train_transforms:
    item_transforms:
      - RandomResizeCrop: { crop_size: [512, 1024], multi_scale: True, ignore_label: 255,
                            min_scale_factor: 0.5, max_scale_factor: 2.0 }
      - RandomFlip: { prob: 0.5 }
      - RandomColor: { contrast_range: [0.4, 1.6] }
      - Normalize: { is_scale: True, norm_type: 'mean_std', mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225] }
      - TransposeImage: { hwc2chw: True }

  eval_transforms:
    img_ratios: [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
    flip: True
    item_transforms:
      - Resize: { target_size: [1024, 2048], keep_ratio: True, ignore_label: 255 }
      - Normalize: { is_scale: True, norm_type: 'mean_std', mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225] }
      - TransposeImage: { hwc2chw: True }
